/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sansapizza;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class Ingraf extends javax.swing.JFrame {
        Local local = new Local();
        private String informacion1;
        private String informacion2;
        private String informacion3;
        private String informacion4;
    /**
     * Creates new form Ingraf
     */
    public Ingraf() {
        initComponents();
        this.informacion1 = "Estrellas Actuales:" + Integer.toString(local.getDineroLocal());
        this.informacion2 = "Popularidad Actual:" + Integer.toString((int)local.getPopularidad());
        this.informacion3 = "Dinero Actual:" + Integer.toString(local.getDineroLocal());
        this.informacion4 = "Clientes Felices 0";
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        Contratar_Cocinero = new javax.swing.JToggleButton();
        Comprar_mesa = new javax.swing.JToggleButton();
        Comprar_Decoracion = new javax.swing.JToggleButton();
        Vender_Mesa = new javax.swing.JToggleButton();
        Vender_decoracion = new javax.swing.JToggleButton();
        LVLup_comida = new javax.swing.JToggleButton();
        Despedir_mesero = new javax.swing.JToggleButton();
        pizza = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Estrellas = new javax.swing.JLabel();
        Dinero = new javax.swing.JLabel();
        Popularidad = new javax.swing.JLabel();
        ClientesFelices = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contratar_Cocinero.setLabel("Contratar Empleado");
        Contratar_Cocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contratar_CocineroActionPerformed(evt);
            }
        });

        Comprar_mesa.setText("Comprar Mesa");
        Comprar_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comprar_mesaActionPerformed(evt);
            }
        });

        Comprar_Decoracion.setText("Comprar Decoracion");
        Comprar_Decoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comprar_DecoracionActionPerformed(evt);
            }
        });

        Vender_Mesa.setText("Vender Mesa");
        Vender_Mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vender_MesaActionPerformed(evt);
            }
        });

        Vender_decoracion.setText("Vender Decoracion");
        Vender_decoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vender_decoracionActionPerformed(evt);
            }
        });

        LVLup_comida.setText("Subir Nivel comida");
        LVLup_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LVLup_comidaActionPerformed(evt);
            }
        });

        Despedir_mesero.setLabel("Despedir Empleado");
        Despedir_mesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Despedir_meseroActionPerformed(evt);
            }
        });

        Estrellas.setText(this.informacion1);

        Dinero.setText(this.informacion4);

        Popularidad.setText(this.informacion2);

        ClientesFelices.setText(this.informacion4);

        jLayeredPane1.setLayer(Estrellas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Dinero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Popularidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ClientesFelices, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ClientesFelices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Popularidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Estrellas, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Estrellas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Popularidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClientesFelices, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pizzaLayout = new javax.swing.GroupLayout(pizza);
        pizza.setLayout(pizzaLayout);
        pizzaLayout.setHorizontalGroup(
            pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        pizzaLayout.setVerticalGroup(
            pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        jToggleButton1.setLabel("Iniciar Dia");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Despedir_mesero)
                            .addComponent(Vender_decoracion)
                            .addComponent(Vender_Mesa)
                            .addComponent(Comprar_mesa)
                            .addComponent(Contratar_Cocinero)
                            .addComponent(LVLup_comida)
                            .addComponent(Comprar_Decoracion))
                        .addGap(24, 24, 24)
                        .addComponent(pizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Contratar_Cocinero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Comprar_mesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Comprar_Decoracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vender_Mesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vender_decoracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LVLup_comida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Despedir_mesero))
                    .addComponent(pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Contratar_CocineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contratar_CocineroActionPerformed
        String[] options = new String[] {"Contratar Mesero", "Contratar Cocinero"};
        int response = JOptionPane.showOptionDialog(null, "Que Empleado Deseas Contratar", "Contratar Empleado",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        local.anadirEmpleado(response);
    }//GEN-LAST:event_Contratar_CocineroActionPerformed

    private void Comprar_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comprar_mesaActionPerformed
        if (local.getMesas().size() == 9) {
            JOptionPane.showMessageDialog(this, "No hay espacio para mesas, vende alguna antes de comprar");
            return;
        }
        String[] options = new String[] {"Comprar Mesa Chica", "Comprar Mesa Mediana", "Comprar Mesa Grande"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Que Tipo de Mesa Deseas Comprar?", "Comprar Mesas",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        local.anadirMesa(respuesta);
    }//GEN-LAST:event_Comprar_mesaActionPerformed

    private void Comprar_DecoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comprar_DecoracionActionPerformed
        String[] options = new String[] {"Comprar Decoracion Regular", "Comprar Decoracion Bonita", "Comprar Decoracion Espectacular"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Que Tipo de Decoracion Deseas Comprar?", "Comprar Decoraciones",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        local.anadirDecoracion(respuesta);
    }//GEN-LAST:event_Comprar_DecoracionActionPerformed

    private void Vender_MesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vender_MesaActionPerformed
        String[] options = new String[] {"Vender Mesa Chica", "Vender Mesa Mediana", "Vender Mesa Grande"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Que Tipo de Mesa Deseas Vender?", "Vender Mesas",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        local.venderMesas(respuesta);
    }//GEN-LAST:event_Vender_MesaActionPerformed

    private void Vender_decoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vender_decoracionActionPerformed
        String[] options = new String[] {"Vender Decoracion Regular", "Vender Decoracion Bonita", "Vender Decoracion Espectacular"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Que Tipo de Decoracion Deseas Vender?", "Vender Decoraciones",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        local.venderDecoracion(respuesta);
    }//GEN-LAST:event_Vender_decoracionActionPerformed

    private void LVLup_comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LVLup_comidaActionPerformed
        String[] options = new String[] {"Si",  "No"};
        int response = JOptionPane.showOptionDialog(null, "Subir de nivel la comida cuesta $"+Integer.toString(local.getComida().getCostoUpgrade())+".\n ¿Aceptas?", "Subir nivel",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        if (response == 0) local.getComida().aumentarNivel(local);
    }//GEN-LAST:event_LVLup_comidaActionPerformed

    private void Despedir_meseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Despedir_meseroActionPerformed
        String[] options = new String[] {"Despedir Mesero", "Despedir Cocinero"};
        int response = JOptionPane.showOptionDialog(null, "Que Empleado Deseas Despedir", "Despedir Empleado",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
        local.despedirEmpleado(response);
    }//GEN-LAST:event_Despedir_meseroActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        local.iniciarDia();
        this.ActualizarEstado();
        if (local.getDineroLocal() <= 0) JOptionPane.showMessageDialog(this, "Perdiste el juego, no te queda mas plata, tu vida quedo destrozada,\nlo unico que te quedan son los sueños en donde todavia puedes salvar a tu pizzeria...\n¿Quien sabe si logras salvarla alli?");
        if (local.getEstrellas() == 5) JOptionPane.showMessageDialog(this, " Ganaste el juego, Felicidades, puedes seguir jugando para hacer que tu pizzeria sea una de la cual don Fede este orgulloso");
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    private void ActualizarEstado(){
       this.informacion1 = "Estrellas Actuales:" + Integer.toString(local.getEstrellas());
       this.informacion2 = "Popularidad Actual:" + Integer.toString((int)local.getPopularidad());
       this.informacion3 = "Dinero Actual:" + Integer.toString(local.getDineroLocal());
       this.informacion4 = "Clientes Felices:" + Integer.toString(local.getLastDay().getCf());
       this.Estrellas.setText(this.informacion1);
       this.Popularidad.setText(this.informacion2);
       this.Dinero.setText(this.informacion3);
       this.ClientesFelices.setText(this.informacion4);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientesFelices;
    private javax.swing.JToggleButton Comprar_Decoracion;
    private javax.swing.JToggleButton Comprar_mesa;
    private javax.swing.JToggleButton Contratar_Cocinero;
    private javax.swing.JToggleButton Despedir_mesero;
    private javax.swing.JLabel Dinero;
    private javax.swing.JLabel Estrellas;
    private javax.swing.JToggleButton LVLup_comida;
    private javax.swing.JLabel Popularidad;
    private javax.swing.JToggleButton Vender_Mesa;
    private javax.swing.JToggleButton Vender_decoracion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pizza;
    // End of variables declaration//GEN-END:variables
}
